include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    cancel_subscriptions: true
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_single_quotes: true
