name: habito
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.9
  flutter_bloc: ^8.1.3
  go_router: ^16.0.0
  time_range_picker: ^2.3.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  http: ^1.4.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
assets:
  - assets/images/LogoHabitO.jpeg
  - assets/images/screens_readme/

flutter_native_splash:
  color: "#FAF5EE"
  image: assets/images/LogoHabitO.jpeg
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/IconHabitO.png"
