// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjXQ24Vn3YCA9Gs3hmBnJfxp2sVUMgJg',
    appId: '1:472822113982:ios:4b4eea35207760e415a0ef',
    messagingSenderId: '472822113982',
    projectId: 'habito-d6a2b',
    storageBucket: 'habito-d6a2b.firebasestorage.app',
    iosBundleId: 'com.example.habito',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwGdAkRRvnj5ck8pI5oErz7IkKqXthPRY',
    appId: '1:472822113982:android:84553f88a88e0a9315a0ef',
    messagingSenderId: '472822113982',
    projectId: 'habito-d6a2b',
    storageBucket: 'habito-d6a2b.firebasestorage.app',
  );

}